package io.github.droidkaigi.confsched.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val primaryDark = Color(0xFFAFC6FF)
internal val onPrimaryDark = Color(0xFF132F60)
internal val primaryContainerDark = Color(0xFF2D4678)
internal val onPrimaryContainerDark = Color(0xFFD8E2FF)
internal val secondaryDark = Color(0xFFCDBDFF)
internal val onSecondaryDark = Color(0xFF34275E)
internal val secondaryContainerDark = Color(0xFF4B3E76)
internal val onSecondaryContainerDark = Color(0xFFE8DEFF)
internal val tertiaryDark = Color(0xFFB4C5FF)
internal val onTertiaryDark = Color(0xFF1A2D60)
internal val tertiaryContainerDark = Color(0xFF334478)
internal val onTertiaryContainerDark = Color(0xFFDBE1FF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF561E19)
internal val errorContainerDark = Color(0xFF73342D)
internal val onErrorContainerDark = Color(0xFFFFDAD5)
internal val backgroundDark = Color(0xFF121318)
internal val onBackgroundDark = Color(0xFFE2E2E9)
internal val surfaceDark = Color(0xFF101510)
internal val onSurfaceDark = Color(0xFFDFE4DD)
internal val surfaceVariantDark = Color(0xFF3F4849)
internal val onSurfaceVariantDark = Color(0xFFBEC8C9)
internal val surfaceTintDark = Color(0xFF1CE46B)
internal val outlineDark = Color(0xFF899393)
internal val outlineVariantDark = Color(0xFF3F4849)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDFE4DD)
internal val inverseOnSurfaceDark = Color(0xFF2C322D)
internal val inversePrimaryDark = Color(0xFF455E91)
internal val surfaceDimDark = Color(0xFF101510)
internal val surfaceBrightDark = Color(0xFF353A36)
internal val surfaceContainerLowestDark = Color(0xFF0A0F0B)
internal val surfaceContainerLowDark = Color(0xFF181D18)
internal val surfaceContainerDark = Color(0xFF1C211C)
internal val surfaceContainerHighDark = Color(0xFF262B27)
internal val surfaceContainerHighestDark = Color(0xFF313631)
