name: spotless-check

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '.github/workflows/spotless.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for clone

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ./.github/actions/setup-java

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck

      - name: Save PR number
        if: always()
        run: |
          echo ${{ github.event.pull_request.number }} > pr_number.txt
      - name: Upload PR number
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pr_number
          path: pr_number.txt
